version: '3'
services:
  postgre:
    restart: always
    image: postgres
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  api:
    restart: always
    build: ./
    depends_on:
      - postgre
    ports:
      - 8080:8080
    environment:
      - DB_PORT=5432
      - DB_HOST=postgre
  adminer:
    restart: always
    image: adminer
    ports:
      - 2222:8080
